language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

addons:
  apt:
    packages:
      - cmake
      - swig
      - libasound2-dev
      - libunittest++-dev
      - doxygen
      - graphviz

before_install:
  - pwd
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install swig; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install unittestcpp; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install doxygen; fi

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_BUILD_TYPE:STRING="Debug" ../
  - make VERBOSE=1
  - make doc
  - make install DESTDIR=dist/

notifications:
  email: false

env:
  global:
  - TRAVIS_LIBOPENSHOT=TEST
  - LANG="en_US.UTF-8"
