language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
    - os: windows
      env: GENTYPE="-G \"MinGW Makefiles\""

addons:
  apt:
    packages:
      - cmake
      - swig
      - libasound2-dev
      - libunittest++-dev
      - doxygen
      - graphviz

cache:
  branch: bash
  directories:
    - /c/msys64

before_install:
  - pwd
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install swig unittest-cpp doxygen
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install msys2 --params "/InstallDir:C:\\msys64"
      #choco install swig doxygen.install
      pacman -Sy mingw-w64-x86_64-toolchain
      pacman -S mingw-w64-x86_64-swig
    fi
    #  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install unittest; fi

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_INSTALL_PREFIX:PATH="$TRAVIS_OS_NAME-x64" -DCMAKE_BUILD_TYPE:STRING="Debug" $GENTYPE ../
  - make VERBOSE=1
  - make doc
  - make install 

notifications:
  email: false

env:
  global:
  - TRAVIS_LIBOPENSHOT=TEST
  - LANG="en_US.UTF-8"
