language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

addons:
  apt:
    packages:
      - cmake
      - swig
      - libasound2-dev
      - libunittest++-dev
      - doxygen
      - graphviz

  homebrew:
    update: true
    packages:
      - gcc
      - unittest-cpp
      - swig

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_INSTALL_PREFIX:PATH="$TRAVIS_OS_NAME-x64" -DCMAKE_BUILD_TYPE:STRING="Debug" ../
  - make VERBOSE=1
  - if [ $TRAVIS_OS_NAME = linux ]; then make doc; fi
  - make install

notifications:
  email: false
