language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - cmake
          - swig
          - libasound2-dev
          - libunittest++-dev
          - doxygen
          - graphviz

    - os: osx
      addons:
        homebrew:
          update: true
          packages:
          - unittest-cpp
          - swig
          - doxygen

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_INSTALL_PREFIX:PATH="$TRAVIS_OS_NAME-x64" -DCMAKE_BUILD_TYPE:STRING="Debug" ../
  - make VERBOSE=1
  - make doc
  - make install

notifications:
  email: false
