version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
before_build:
- cmd: >-
        set PATH=C:\MSYS64\mingw64\bin;c:\msys64\mingw64\lib;%PATH%

        c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-toolchain base-devel"

build_script:
- cmd: >-
    set PATH=%PATH:C:\Program Files\Git\bin;=%

    mkdir build

    cd build

    cmake  -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_INSTALL_PREFIX:PATH=install-x64 -G "MinGW Makefiles"  ../

    mingw32-make VERBOSE=1

    mingw32-make install

test: off
deploy: off
