version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
build_script:
- sh: >-
    mkdir build

    cd build

    cmake  -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX:PATH=install-x64 -G "MinGW Makefiles"  ../

    mingw32-make VERBOSE=1

    mingw32-make install
test: off