version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build:
    publish_nuget: true
    publish_nuget_symbols: true
before_build:
- cmd: >-
        set PATH=C:\MSYS64\mingw64\bin;c:\msys64\mingw64\lib;%PATH%

        c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-toolchain base-devel"

build_script:
- cmd: >-
    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    mkdir build

    cd build

    cmake  -DCMAKE_INSTALL_PREFIX:PATH=install-x64 -G "MinGW Makefiles"  ..

    mingw32-make VERBOSE=1

    mingw32-make install

    nuget pack

#   appveyor PushArtifact libopenshot-audio.1.1.8-dev1.nupkg

test: off

artifacts:
  - path: 'build\install-x64'
    name: libopenshot-audio-install
    type: Zip

# deploy:
#   - provider: NuGet
#     symbol_server: $(ACCOUNT_NUGET_FEED_URL)/api/v2/package
#     api_key:
#       secure: $(SECURE_NUGET_API_KEY)
#     artifact: /build/.*\.nupkg/
