name: 'ci-build-and-release'
on:
  push:
    branches:
      - ci-artifacts
  pull_request:
    branches:
      - develop
      - ci-artifacts

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        compiler: [gcc]
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Linux dependencies
        if: ${{ runner.os == 'linux' }}
        run: |
          sudo apt update
          sudo apt install cmake doxygen graphviz
          sudo apt install libasound2-dev

      - name: macOS dependencies
        if: ${{ runner.os == 'macos' }}
        run: |
          brew install doxygen

      - name: Windows dependencies
        if: ${{ runner.os == 'windows' }}
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          install: >-
            mingw-w64-x86_64-${{ matrix.compiler }}
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-extra-cmake-modules
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-python3
            doxygen

      - name: Build (Unix)
        if: ${{ runner.os != 'windows' }}
        run: |
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX:PATH="${{ github.workspace }}/dist/OpenShotAudio" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE:BOOL=1 -DAUDIO_DOCS_AUTO_INSTALL=0
          cmake --build build
          cmake --build build --target OpenShotAudio-doc
          cmake --install build
          cd dist
          zip -rm "OpenShotAudio.zip" "OpenShotAudio"

      - name: Build (Windows)
        if: ${{ runner.os == 'windows' }}
        shell: msys2 {0}
        run: |
          cmake -B build -S . -G "MinGW Makefiles" "-DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/dist/OpenShotAudio" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_VERBOSE_MAKEFILE:BOOL=1" "-DAUDIO_DOCS_AUTO_INSTALL=0"
          cmake --build build
          cmake --install build
          cd dist
          zip -rm "OpenShotAudio.zip" "OpenShotAudio"

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'OpenShotAudio-${{ matrix.os }}-${{ matrix.compiler }}'
          path: '${{ github.workspace }}/dist/OpenShotAudio.zip'

  release:
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
        # action-recreate-release needs access to .git/refs/tags
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Recreate latest CI release
        id: create_release
        uses: GongT/actions-recreate-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ci_latest
          release_name: Continuous Integration - latest builds
          body: Snapshot of ${{ github.ref }}.
          draft: false
          prerelease: true

  upload:
    runs-on: ubuntu-latest
    needs: [build, release]
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        compiler: [gcc]
    steps:
      - name: Download our artifact
        uses: actions/download-artifact@v2
        with:
          name: 'OpenShotAudio-${{ matrix.os }}-${{ matrix.compiler }}'
          path: dist/

      - name: Add files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: 'dist/OpenShotAudio.zip'
          asset_name: 'OpenShotAudio-${{ matrix.os }}-${{ matrix.compiler }}.zip'
          asset_content_type: application/zip
