name: 'Linux-ci'
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compiler: [gcc, clang]
    steps:
    - name: Check out branch
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install cmake doxygen graphviz
        sudo apt install libasound2-dev

    - name: Build
      run: |
        mkdir build
        pushd build
        cmake -B . -S .. \
          -DCMAKE_INSTALL_PREFIX:PATH="dist" \
          -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_VERBOSE_MAKEFILE:BOOL=1 \
          -DAUTO_INSTALL_DOCS=0
        cmake --build . -- VERBOSE=1
        popd

    - name: Generate API documentation
      run: |
        pushd build
        cmake --build . --target doc
        popd

    - name: Install
      run: |
        pushd build
        cmake --build . --target install
        popd

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'OpenShotAudio-${{ matrix.os }}-${{ matrix.compiler }}'
        path: ${{ github.workspace }}/build/dist/
