name: 'macos-ci'
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - name: Check out branch
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        brew update
        brew install doxygen

    - name: Build
      run: |
        cmake -B build -S . \
        -DCMAKE_INSTALL_PREFIX:PATH="build/dist" \
        -DCMAKE_BUILD_TYPE="Debug" \
        -DAUTO_INSTALL_DOCS=0
        cmake --build build -- VERBOSE=1

    - name: Generate API documentation
      run: cmake --build build --target doc

    - name: Install
      run: cmake --build . --target install -- VERBOSE=1

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'OpenShotAudio-${{ matrix.os }}-${{ matrix.compiler }}'
        path: ${{ github.workspace }}/build/dist/
